"use client";
import { useEffect, useRef, useState } from "react";

type Calendar = "SOLAR" | "LUNAR"; type Mode = "solar" | "lunar" | "leap";
export function BirthDateField({value,calendar,leap,onChange}:{value:string;calendar:Calendar;leap:boolean;onChange:(date:string,calendar:Calendar,leap:boolean)=>void}){
  const [open,setOpen]=useState(false),[year,setYear]=useState(2000),[month,setMonth]=useState(1),[day,setDay]=useState(1); const [mode,setMode]=useState<Mode>("solar");
  function show(){const [y,m,d]=value.split("-").map(Number);setYear(y);setMonth(m);setDay(d);setMode(calendar==="SOLAR"?"solar":leap?"leap":"lunar");setOpen(true)}
  const maximumDay=mode==="solar"?new Date(year,month,0).getDate():30; useEffect(()=>{if(day>maximumDay)setDay(maximumDay)},[day,maximumDay]);
  function confirm(){onChange(`${year}-${pad(month)}-${pad(day)}`,mode==="solar"?"SOLAR":"LUNAR",mode==="leap");setOpen(false)}
  const modes:Mode[]=["solar","lunar","leap"];
  return <><button type="button" className="picker-value" onClick={show}>{formatDate(value)}</button>{open&&<PickerOverlay title="생년월일 선택" onClose={()=>setOpen(false)} onConfirm={confirm}><div className="custom-wheels date-wheels"><WheelColumn values={[0,1,2]} value={modes.indexOf(mode)} labels={["양력","음력","윤달"]} onChange={index=>setMode(modes[index])}/><WheelColumn values={range(mode==="solar"?1926:1925,2027)} value={year} suffix="년" onChange={setYear}/><WheelColumn values={range(1,12)} value={month} suffix="월" onChange={setMonth}/><WheelColumn values={range(1,maximumDay)} value={day} suffix="일" onChange={setDay}/></div></PickerOverlay>}</>;
}
export function BirthTimeField({value,onChange}:{value:string;onChange:(time:string)=>void}){
  const [open,setOpen]=useState(false),[period,setPeriod]=useState(0),[hour,setHour]=useState(12),[minute,setMinute]=useState(0);
  function show(){const [h,m]=value.split(":").map(Number);setPeriod(h<12?0:1);setHour(h%12||12);setMinute(m);setOpen(true)}
  function confirm(){onChange(`${pad(hour%12+period*12)}:${pad(minute)}`);setOpen(false)}
  return <><button type="button" className="picker-value" onClick={show}>{formatTime(value)}</button>{open&&<PickerOverlay title="태어난 시간 선택" onClose={()=>setOpen(false)} onConfirm={confirm}><div className="custom-wheels time-wheels"><WheelColumn values={[0,1]} value={period} labels={["오전","오후"]} onChange={setPeriod}/><WheelColumn values={range(1,12)} value={hour} suffix="시" onChange={setHour}/><WheelColumn values={range(0,59)} value={minute} suffix="분" padValue onChange={setMinute}/></div></PickerOverlay>}</>;
}
function PickerOverlay({title,onClose,onConfirm,children}:{title:string;onClose:()=>void;onConfirm:()=>void;children:React.ReactNode}){return <div className="picker-overlay" onClick={onClose}><button type="button" className="picker-confirm" onClick={event=>{event.stopPropagation();onConfirm()}} aria-label="선택 완료">✓</button><section className="picker-sheet" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}>{children}</section></div>}
function WheelColumn({values,value,suffix="",labels,padValue=false,onChange}:{values:number[];value:number;suffix?:string;labels?:string[];padValue?:boolean;onChange:(value:number)=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const index=values.indexOf(value);if(index>=0)ref.current?.scrollTo({top:index*46})},[value,values]);return <div className="custom-wheel" ref={ref} onScroll={event=>{const index=Math.max(0,Math.min(values.length-1,Math.round(event.currentTarget.scrollTop/46)));if(values[index]!==value)onChange(values[index])}}>{values.map((item,index)=><button type="button" data-active={item===value} className={item===value?"active":""} onClick={()=>onChange(item)} key={item}>{labels?.[index]??`${padValue?pad(item):item}${suffix}`}</button>)}</div>}
function range(start:number,end:number){return Array.from({length:end-start+1},(_,index)=>start+index)} function pad(value:number){return String(value).padStart(2,"0")} function formatDate(value:string){const [y,m,d]=value.split("-").map(Number);return `${y}. ${m}. ${d}.`} function formatTime(value:string){const [h,m]=value.split(":").map(Number);return `${String(h%12||12).padStart(2,"0")}:${pad(m)} ${h<12?"AM":"PM"}`}
