"use client";
import { FormEvent, useEffect, useState } from "react"; import { Header } from "@/components/Header"; import { api, hasToken, Profile } from "@/lib/api"; import { useRouter } from "next/navigation";
import { BirthDateField, BirthTimeField } from "@/components/BirthPickers";
const EMPTY:Profile={displayName:"",birthDate:"2000-01-01",birthTime:"12:00",calendarType:"SOLAR",leapMonth:false,gender:"FEMALE"};
export default function ProfilePage() { const router = useRouter(); const [profile, setProfile] = useState<Profile>(EMPTY); const [savedProfile,setSavedProfile]=useState<Profile>(EMPTY); const [message, setMessage] = useState(""); const dirty=JSON.stringify(profile)!==JSON.stringify(savedProfile);
  useEffect(() => { if (!hasToken()) { router.replace("/login"); return; } api<Profile>("/api/profile", {}, true).then(p => {const loaded={...p,birthTime:p.birthTime.slice(0,5)};setProfile(loaded);setSavedProfile(loaded)}).catch(() => {}); }, [router]);
  async function submit(e: FormEvent) { e.preventDefault(); try { const saved = await api<Profile>("/api/profile", { method: "PUT", body: JSON.stringify({ ...profile, birthTime: `${profile.birthTime}:00` }) }, true); const loaded={...saved,birthTime:saved.birthTime.slice(0,5)};setProfile(loaded);setSavedProfile(loaded);setMessage("프로필이 저장되었습니다."); } catch (x) { setMessage(x instanceof Error ? x.message : "저장하지 못했습니다."); } }
  return <main className="app-shell form-shell"><Header title="내 정보" />{dirty&&<button type="submit" form="profile-form" className="profile-save" aria-label="저장">✓</button>}<form id="profile-form" className="center-form maui-form profile-form" onSubmit={submit}><label><strong>성명</strong><input placeholder="성명" value={profile.displayName} onChange={e => setProfile({...profile, displayName:e.target.value})} required /></label><div className="profile-row"><strong>성별</strong><div className="gender-options"><label><input type="radio" checked={profile.gender === "MALE"} onChange={() => setProfile({...profile, gender:"MALE"})} /><i/>남</label><label><input type="radio" checked={profile.gender === "FEMALE"} onChange={() => setProfile({...profile, gender:"FEMALE"})} /><i/>여</label></div></div><div className="profile-row"><strong>생년월일</strong><BirthDateField value={profile.birthDate} calendar={profile.calendarType} leap={profile.leapMonth} onChange={(birthDate,calendarType,leapMonth)=>setProfile({...profile,birthDate,calendarType,leapMonth})}/></div><div className="profile-row"><strong>태어난 시</strong><BirthTimeField value={profile.birthTime} onChange={birthTime=>setProfile({...profile,birthTime})}/></div>{message && <p className="status">{message}</p>}</form></main>;
}
