ALTER TABLE daily_fortunes
    ALTER COLUMN overall TYPE INTEGER,
    ALTER COLUMN wealth TYPE INTEGER,
    ALTER COLUMN love TYPE INTEGER,
    ALTER COLUMN health TYPE INTEGER,
    ALTER COLUMN career TYPE INTEGER,
    ALTER COLUMN relationships TYPE INTEGER,
    ALTER COLUMN study TYPE INTEGER,
    ALTER COLUMN annual_rank TYPE INTEGER,
    ALTER COLUMN annual_total_days TYPE INTEGER,
    ALTER COLUMN annual_top_percent TYPE INTEGER;
